version: "3.9"
   
services:
  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      - PUID=1000
      - PGID=1000
  web:
    build: .
    command: sh -c "
      sleep 3 &&
      npm install && 
      npm start"
    #command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db