version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: sh -c "
      sleep 3 &&
      npm install && 
      npm run dev"
    #command: npm run dev
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db